export const handyMen = [{"first_name":"Jessika","last_name":"Bulcroft","phone_number":"574-571-8935","pay_rate":9.41,"skills":["Tile Installer"]},
{"first_name":"Alwyn","last_name":"Fewkes","phone_number":"713-481-7874","pay_rate":35.62,"skills":["Electrician"]},
{"first_name":"Laetitia","last_name":"Gladbach","phone_number":"426-734-5445","pay_rate":30.85,"skills":["Electrician"]},
{"first_name":"Ewan","last_name":"Fenning","phone_number":"464-780-2206","pay_rate":3.59,"skills":["Drywall Installer","Landscaper","Plumber"]},
{"first_name":"Rozanna","last_name":"Heintz","phone_number":"747-243-7691","pay_rate":22.81,"skills":["Landscaper","Electrician"]},
{"first_name":"Cathee","last_name":"Streader","phone_number":"304-749-4961","pay_rate":48.33,"skills":["Drywall Installer","Landscaper","Electrician"]},
{"first_name":"Gabi","last_name":"Patzelt","phone_number":"668-584-0549","pay_rate":40.57,"skills":["Drywall Installer"]},
{"first_name":"Donal","last_name":"Jancic","phone_number":"422-110-2198","pay_rate":25.49,"skills":["Electrician","Drywall Installer"]},
{"first_name":"Ode","last_name":"Aime","phone_number":"766-880-3033","pay_rate":47.58,"skills":["Electrician"]},
{"first_name":"Stephen","last_name":"Wilce","phone_number":"754-398-9852","pay_rate":39.81,"skills":["Electrician","Drywall Installer","Tile Installer"]},
{"first_name":"Sebastian","last_name":"Keling","phone_number":"779-243-8720","pay_rate":27.02,"skills":["Tile Installer","Drywall Installer","Electrician"]},
{"first_name":"Alexia","last_name":"Honatsch","phone_number":"363-417-6682","pay_rate":22.89,"skills":["Landscaper","Electrician","Plumber"]},
{"first_name":"Grazia","last_name":"Lancley","phone_number":"743-132-4261","pay_rate":18.79,"skills":["Drywall Installer","Plumber","Electrician"]},
{"first_name":"Emmott","last_name":"Burlay","phone_number":"341-150-6901","pay_rate":38.3,"skills":["Electrician","Tile Installer"]},
{"first_name":"Willabella","last_name":"Trow","phone_number":"151-205-5884","pay_rate":1.64,"skills":["Drywall Installer","Electrician","Plumber"]}];